FROM ubuntu:24.04

# The following line is used for GitHub Actions --------------
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

# -------------------------------------------------------------

# Add your dockerfile commands here

CMD ["/bin/bash"]
