FROM ubuntu:24.04

# The following line is used for GitHub Actions --------------
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

# -------------------------------------------------------------

# Install system dependencies and Python3
RUN apt-get -y update && apt-get install -y \
    gcc \
    curl \
    wget \
    bash \
    jq \
    libffi-dev \
    libssl-dev \
    software-properties-common \
    python3 \
    pip \
    gnupg \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Install Terraform
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add - \
    && apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
    && apt-get update && apt-get install -y terraform=1.9.8-*

CMD ["/bin/bash"]
